"""Generate backend/schema.sql from the real dataframes.

Hand-typing ~150 column definitions across 13 tables is an invitation to a
typo that surfaces as a runtime insert error on deadline day. The column names
and types are derived from the actual pipeline output instead, so the schema
cannot drift from the data. Primary keys and indexes ARE declared by hand --
they encode intent (dedupe by doc_no) and must not be inferred.

Run:  python backend/make_schema.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
CLEAN = ROOT / "data" / "clean"
APP = ROOT / "data" / "app"
OUT = Path(__file__).resolve().parent / "schema.sql"

# table -> (source csv, primary key columns, extra indexes)
# The PK on sales_header/sales_lines/deposits is what makes re-uploading the
# same Express export idempotent: ON CONFLICT ... DO UPDATE, keyed by doc_no.
TABLES = {
    "sales_header":         (CLEAN / "sales_header.csv",        ["doc_no"],                 ["doc_date_iso", "customer_code", "sale_type"]),
    "sales_lines":          (CLEAN / "sales_lines.csv",         ["doc_no", "line_no"],      ["doc_date_iso", "sku_prefix", "customer_code", "sku"]),
    "deposits":             (CLEAN / "deposits.csv",            ["doc_no"],                 ["customer_code"]),
    "deposit_applications": (CLEAN / "deposit_applications.csv", ["deposit_doc_no", "applied_doc_no"], ["customer_code"]),
    "products":             (CLEAN / "products.csv",            ["sku"],                    ["sku_prefix"]),
    "customers":            (CLEAN / "customers.csv",           ["customer_name"],          ["customer_code"]),
    "customer_rfm":         (CLEAN / "customer_rfm.csv",        ["customer_code"],          ["segment", "monetary"]),
    "customer_segments":    (CLEAN / "customer_segments.csv",   ["segment"],                []),
    # data/app, not data/clean. Both directories hold a weekly_demand.csv with
    # different contents; the dashboard contract is the one that gets served.
    # See the note in backend/app/ingest.py APP_TO_DB.
    "weekly_demand":        (APP / "weekly_demand.csv",         ["sku_prefix", "week_start"], []),
    "monthly_sales":        (CLEAN / "monthly_sales.csv",       None,                       []),
    "forecast_next_4_weeks": (APP / "forecast_next_4_weeks.csv", ["sku_prefix"],            []),
    "trend_alerts":         (APP / "trend_alerts.csv",          ["sku_prefix"],             []),
    "reorder_points":       (APP / "reorder_points.csv",        ["sku_prefix"],             []),
    "stock_check":          (APP / "stock_check.csv",           ["sku"],                    ["risk_level"]),
    # Pages 1 and 2 read these three. They were missing until after the first
    # live load: all local testing ran in CSV-fallback mode, where the API
    # never touches Postgres, so the gap was invisible until DATABASE_URL was
    # set -- which is to say, it would first have appeared in production.
    "kpi_monthly":          (APP / "kpi_monthly.csv",           ["month"],                  []),
    "sales_by_group_month": (APP / "sales_by_group_month.csv",  ["month", "category", "group_name"], ["month"]),
    "sales_by_person_month": (APP / "sales_by_person_month.csv", ["month", "salesperson_code"], []),
    "model_accuracy":       (APP / "model_accuracy.csv",        None,                       []),
    "model_accuracy_pooled": (APP / "model_accuracy_pooled.csv", ["scenario", "model"],     []),
    "dim_product_group":    (APP / "dim_product_group.csv",     ["sku_prefix"],             []),
}

# Columns that look numeric but are identifiers and must stay text.
FORCE_TEXT = {
    "sku_prefix", "salesperson_code", "customer_code", "doc_no", "sku",
    "voucher_no", "sales_order", "so_ref", "rfm_score", "month", "week_start",
    "doc_date", "doc_date_iso", "due_date", "due_date_iso", "last_purchase",
    "first_purchase", "last_sale_date", "as_of",
}


def sql_type(name: str, s: pd.Series) -> str:
    if name in FORCE_TEXT:
        return "text"
    # An all-empty column carries no evidence of its type -- pandas calls it
    # float64 by default, which is a guess, and a wrong guess costs a failed
    # upload against a live database. text accepts anything a later export
    # puts there, and nothing downstream does arithmetic on a column that has
    # never held a number.
    if s.isna().all():
        return "text"
    if pd.api.types.is_bool_dtype(s):
        return "boolean"
    if pd.api.types.is_integer_dtype(s):
        return "bigint"
    if pd.api.types.is_float_dtype(s):
        return "double precision"
    return "text"


def quote(name: str) -> str:
    return f'"{name}"'


def main() -> int:
    parts: list[str] = [
        "-- Schema for the Express analytics web app.",
        "-- GENERATED by backend/make_schema.py -- edit that, not this file.",
        "--",
        "-- Run this once in the Supabase SQL editor (or psql) before the first upload.",
        "-- Safe to re-run: every statement is IF NOT EXISTS / OR REPLACE.",
        "",
        "create extension if not exists pgcrypto;",
        "",
        "-- Audit trail: one row per upload, so a bad import can be traced and undone.",
        "create table if not exists upload_batches (",
        "    id            uuid primary key default gen_random_uuid(),",
        "    uploaded_at   timestamptz not null default now(),",
        "    uploaded_by   text,",
        "    filenames     text,",
        "    n_cash        bigint,",
        "    n_credit      bigint,",
        "    n_deposit     bigint,",
        "    revenue_ex_vat double precision,",
        "    status        text,",
        "    message       text",
        ");",
        "",
    ]

    missing = []
    problems: list[str] = []
    for table, (path, pk, idx) in TABLES.items():
        if not path.exists():
            missing.append(f"{table} <- {path.relative_to(ROOT)}")
            continue
        # Read the WHOLE file, not a sample. A 2000-row sample typed
        # sales_header.collected_flag as double precision because the flag is
        # empty until row 6089, where a "Y" appears -- and COPY then rejected
        # the real upload. Type inference must see every row it will have to
        # store. The largest table here is 31k rows; the cost is a second.
        df = pd.read_csv(path)

        # A primary key naming a column that does not exist produces SQL that
        # fails at CREATE TABLE -- i.e. it breaks the very first deploy step,
        # in the Supabase console, where the error is least welcome. These
        # keys are hand-declared, so validate them against the real columns.
        if pk:
            unknown = [c for c in pk if c not in df.columns]
            if unknown:
                problems.append(
                    f"{table}: primary key names column(s) {unknown} which are "
                    f"not in {path.name}. Columns are: {list(df.columns)}"
                )
                continue
            full = pd.read_csv(path, dtype=str)
            dups = int(full.duplicated(subset=pk).sum())
            if dups:
                problems.append(
                    f"{table}: {dups} duplicate rows for primary key {pk}. "
                    f"INSERT ... ON CONFLICT DO UPDATE cannot touch the same "
                    f"row twice in one statement, so the upload would fail."
                )
                continue

        cols = []
        for c in df.columns:
            t = sql_type(c, df[c])
            nn = " not null" if pk and c in pk else ""
            cols.append(f"    {quote(c):<34} {t}{nn}")
        body = ",\n".join(cols)
        if pk:
            body += f",\n    primary key ({', '.join(quote(c) for c in pk)})"
        parts.append(f"create table if not exists {table} (\n{body}\n);")
        for c in idx:
            if c in df.columns:
                parts.append(
                    f"create index if not exists idx_{table}_{c} on {table} ({quote(c)});"
                )
        parts.append("")

    if missing:
        print("ERROR: missing source files -- run the pipeline first:", file=sys.stderr)
        for m in missing:
            print(f"   {m}", file=sys.stderr)
        return 1

    if problems:
        print("ERROR: schema would not apply cleanly:", file=sys.stderr)
        for p in problems:
            print(f"   {p}", file=sys.stderr)
        print("\nNo file written.", file=sys.stderr)
        return 1

    # Row Level Security. Supabase exposes every table over PostgREST with the
    # anon key -- which ships to the browser -- so without policies the whole
    # dataset is readable by anyone who finds the project URL.
    #
    # These used to all be `using (true)`: any signed-in user, the entire
    # dataset. That is precisely what migration 004 exists to stop, so the
    # rules are emitted here too. If they lived only in the migration,
    # re-running this generator would quietly hand the company's revenue back
    # to every salesperson, and nothing would fail to warn anybody.
    #
    # The predicate functions (app_can_see, app_is_ceo, app_role) are created
    # by 004_row_level_visibility.sql, which must be applied first.
    parts += [
        "-- ---------------------------------------------------------------",
        "-- Row Level Security -- see migrations/004_row_level_visibility.sql,",
        "-- which creates the app_can_see() / app_is_ceo() predicates these",
        "-- policies call. Apply that migration before this file.",
        "--",
        "-- The backend connects as service_role and BYPASSES all of this.",
        "-- These policies are the second layer: they are what stops the anon",
        "-- key, which is public, from reading the data directly.",
        "-- ---------------------------------------------------------------",
        "",
    ]
    # Carries salesperson_code -> filter row by row.
    ROW_SCOPED = {"sales_header", "sales_lines", "sales_by_person_month"}
    # Company-wide totals with nothing to filter on -> ceo only. The API
    # recomputes the others' equivalents from sales_lines (app/views.py).
    CEO_ONLY = {
        "kpi_monthly", "sales_by_group_month", "customer_rfm",
        "customer_segments", "customers", "monthly_sales", "deposits",
        "deposit_applications", "upload_batches",
    }
    for table in list(TABLES) + ["upload_batches"]:
        if table in ROW_SCOPED:
            using = "app_can_see(salesperson_code)"
        elif table in CEO_ONLY:
            using = "app_is_ceo()"
        else:
            # Product reference / demand / forecast: no person's revenue in
            # them. Any user who has been given a role may read them; the
            # page-level gate for the sales role is a config flag in the API.
            using = "app_role() <> 'none'"
        parts.append(f"alter table {table} enable row level security;")
        parts.append(
            f"drop policy if exists {table}_read on {table};\n"
            f"create policy {table}_read on {table} for select "
            f"to authenticated using ({using});"
        )
    parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    n_tables = len(TABLES) + 1
    print(f"Wrote {OUT.relative_to(ROOT)}  ({n_tables} tables, {len(parts)} statements)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
