-- Schema for the Express analytics web app.
-- GENERATED by backend/make_schema.py -- edit that, not this file.
--
-- Run this once in the Supabase SQL editor (or psql) before the first upload.
-- Safe to re-run: every statement is IF NOT EXISTS / OR REPLACE.

create extension if not exists pgcrypto;

-- Audit trail: one row per upload, so a bad import can be traced and undone.
create table if not exists upload_batches (
    id            uuid primary key default gen_random_uuid(),
    uploaded_at   timestamptz not null default now(),
    uploaded_by   text,
    filenames     text,
    n_cash        bigint,
    n_credit      bigint,
    n_deposit     bigint,
    revenue_ex_vat double precision,
    status        text,
    message       text
);

create table if not exists sales_header (
    "doc_no"                           text not null,
    "sale_type"                        text,
    "doc_date"                         text,
    "doc_date_iso"                     text,
    "customer_code"                    text,
    "customer_name"                    text,
    "salesperson_code"                 text,
    "name_truncated"                   boolean,
    "vat_flag"                         bigint,
    "discount"                         double precision,
    "discount_pct"                     double precision,
    "goods_value"                      double precision,
    "vat"                              double precision,
    "total"                            double precision,
    "overpaid"                         double precision,
    "received_cash"                    double precision,
    "received_cheque"                  double precision,
    "withholding_tax"                  double precision,
    "due_date"                         text,
    "due_date_iso"                     text,
    "sales_order"                      text,
    "collected_flag"                   text,
    "is_cancelled"                     boolean,
    "remark"                           text,
    "vat_inclusive"                    boolean,
    primary key ("doc_no")
);
create index if not exists idx_sales_header_doc_date_iso on sales_header ("doc_date_iso");
create index if not exists idx_sales_header_customer_code on sales_header ("customer_code");
create index if not exists idx_sales_header_sale_type on sales_header ("sale_type");

create table if not exists sales_lines (
    "doc_no"                           text not null,
    "line_no"                          bigint not null,
    "sku"                              text,
    "product_name"                     text,
    "qty"                              double precision,
    "unit"                             text,
    "unit_price"                       double precision,
    "discount"                         text,
    "amount"                           double precision,
    "so_ref"                           text,
    "sale_type"                        text,
    "vat_inclusive"                    boolean,
    "amount_ex_vat"                    double precision,
    "is_cancelled"                     boolean,
    "sku_prefix"                       text,
    "category"                         text,
    "group_name"                       text,
    "doc_date"                         text,
    "doc_date_iso"                     text,
    "salesperson_code"                 text,
    "customer_code"                    text,
    primary key ("doc_no", "line_no")
);
create index if not exists idx_sales_lines_doc_date_iso on sales_lines ("doc_date_iso");
create index if not exists idx_sales_lines_sku_prefix on sales_lines ("sku_prefix");
create index if not exists idx_sales_lines_customer_code on sales_lines ("customer_code");
create index if not exists idx_sales_lines_sku on sales_lines ("sku");

create table if not exists deposits (
    "doc_no"                           text not null,
    "customer_code"                    text,
    "customer_name"                    text,
    "doc_date"                         text,
    "doc_date_iso"                     text,
    "salesperson_code"                 text,
    "vat_flag"                         bigint,
    "value"                            double precision,
    "vat"                              double precision,
    "total"                            double precision,
    "due_date"                         text,
    "due_date_iso"                     text,
    "outstanding"                      double precision,
    "cleared_flag"                     text,
    "received_cash"                    double precision,
    "received_cheque"                  double precision,
    "is_cancelled"                     boolean,
    "description"                      text,
    primary key ("doc_no")
);
create index if not exists idx_deposits_customer_code on deposits ("customer_code");

create table if not exists deposit_applications (
    "deposit_doc_no"                   text not null,
    "applied_doc_no"                   text not null,
    "applied_date"                     text,
    "applied_date_iso"                 text,
    "cleared_date"                     text,
    "cleared_date_iso"                 text,
    "amount"                           double precision,
    "customer_code"                    text,
    "sources"                          text,
    "amount_max_spread"                double precision,
    "doc_type"                         text,
    primary key ("deposit_doc_no", "applied_doc_no")
);
create index if not exists idx_deposit_applications_customer_code on deposit_applications ("customer_code");

create table if not exists products (
    "sku"                              text not null,
    "sku_prefix"                       text,
    "product_name"                     text,
    "unit"                             text,
    "item_type"                        text,
    "is_inventory"                     boolean,
    "n_lines"                          bigint,
    "n_name_variants"                  bigint,
    "pct_unpriced"                     double precision,
    "total_qty"                        double precision,
    "total_revenue_ex_vat"             double precision,
    "category"                         text,
    "group_name"                       text,
    primary key ("sku")
);
create index if not exists idx_products_sku_prefix on products ("sku_prefix");

create table if not exists customers (
    "customer_code"                    text,
    "customer_name"                    text not null,
    "code_source"                      text,
    primary key ("customer_name")
);
create index if not exists idx_customers_customer_code on customers ("customer_code");

create table if not exists customer_rfm (
    "customer_code"                    text not null,
    "customer_name"                    text,
    "segment"                          text,
    "segment_th"                       text,
    "recency_days"                     bigint,
    "frequency"                        bigint,
    "monetary"                         double precision,
    "avg_order_value"                  double precision,
    "r_score"                          bigint,
    "f_score"                          bigint,
    "m_score"                          bigint,
    "fm_score"                         double precision,
    "rfm_score"                        text,
    "last_purchase"                    text,
    "first_purchase"                   text,
    "tenure_days"                      bigint,
    "revenue_rank"                     bigint,
    "revenue_share_pct"                double precision,
    "cumulative_revenue_pct"           double precision,
    primary key ("customer_code")
);
create index if not exists idx_customer_rfm_segment on customer_rfm ("segment");
create index if not exists idx_customer_rfm_monetary on customer_rfm ("monetary");

create table if not exists customer_segments (
    "segment"                          text not null,
    "segment_th"                       text,
    "n_customers"                      bigint,
    "revenue"                          double precision,
    "avg_recency_days"                 bigint,
    "avg_frequency"                    double precision,
    "avg_order_value"                  double precision,
    "customer_share_pct"               double precision,
    "revenue_share_pct"                double precision,
    "revenue_per_customer"             double precision,
    primary key ("segment")
);

create table if not exists weekly_demand (
    "week_start"                       text not null,
    "sku_prefix"                       text not null,
    "group_name"                       text,
    "unit"                             text,
    "qty"                              double precision,
    "is_complete_week"                 boolean,
    "forecast_scope"                   boolean,
    primary key ("sku_prefix", "week_start")
);

create table if not exists monthly_sales (
    "month"                            text,
    "category"                         text,
    "group_name"                       text,
    "salesperson_code"                 text,
    "revenue_ex_vat"                   double precision,
    "n_invoices"                       bigint,
    "n_lines"                          bigint
);

create table if not exists forecast_next_4_weeks (
    "sku_prefix"                       text not null,
    "group_name"                       text,
    "unit"                             text,
    "model"                            text,
    "forecast_from_week"               text,
    "forecast_to_week"                 text,
    "forecast_qty_per_week"            double precision,
    "n_weeks_in_mean"                  bigint,
    "forecast_qty_4wk"                 double precision,
    "low_qty_4wk"                      double precision,
    "high_qty_4wk"                     double precision,
    "ratio_low"                        double precision,
    "ratio_median"                     double precision,
    "ratio_high"                       double precision,
    "n_windows"                        bigint,
    "range_below_forecast"             boolean,
    "is_intermittent"                  boolean,
    "confidence"                       text,
    primary key ("sku_prefix")
);

create table if not exists trend_alerts (
    "sku_prefix"                       text not null,
    "group_name"                       text,
    "unit"                             text,
    "median_qty_last_4wk"              double precision,
    "median_qty_last_8wk"              double precision,
    "median_qty_prior_4wk"             double precision,
    "pct_change_median"                double precision,
    "pct_change_vs_prior_4"            double precision,
    "qty_last_4wk"                     double precision,
    "qty_last_8wk"                     double precision,
    "stopped"                          boolean,
    "avg_qty_last_4wk"                 double precision,
    "avg_qty_last_8wk"                 double precision,
    "avg_qty_prior_4wk"                double precision,
    "pct_change_mean"                  double precision,
    "outlier_driven"                   boolean,
    "alert"                            boolean,
    "direction"                        text,
    "is_intermittent"                  boolean,
    primary key ("sku_prefix")
);

create table if not exists reorder_points (
    "sku_prefix"                       text not null,
    "group_name"                       text,
    "unit"                             text,
    "first_sale_week"                  text,
    "last_sale_week"                   text,
    "n_weeks_panel"                    bigint,
    "n_weeks_pre_launch"               bigint,
    "n_weeks_active"                   bigint,
    "basis_window"                     text,
    "n_weeks"                          bigint,
    "mean_weekly_qty"                  double precision,
    "std_weekly_qty"                   double precision,
    "max_weekly_qty"                   double precision,
    "pct_zero_weeks"                   double precision,
    "mean_weekly_qty_active"           double precision,
    "mean_weekly_qty_last8"            double precision,
    "recent_vs_active"                 double precision,
    "regime_shift"                     boolean,
    "trailing_zero_weeks"              bigint,
    "maybe_discontinued"               boolean,
    "lead_time_weeks"                  bigint,
    "service_level"                    double precision,
    "safety_z"                         double precision,
    "lead_time_demand"                 double precision,
    "safety_stock"                     double precision,
    "reorder_point"                    double precision,
    "weeks_of_cover"                   double precision,
    primary key ("sku_prefix")
);

create table if not exists stock_check (
    "sku"                              text not null,
    "product_name"                     text,
    "unit"                             text,
    "sku_prefix"                       text,
    "category"                         text,
    "group_name"                       text,
    "as_of_date"                       text,
    "last_sale_date"                   text,
    "days_since_last_sale"             bigint,
    "risk_level"                       text,
    "recommendation"                   text,
    "total_qty_sold"                   double precision,
    "total_revenue_ex_vat"             double precision,
    "n_documents"                      bigint,
    primary key ("sku")
);
create index if not exists idx_stock_check_risk_level on stock_check ("risk_level");

create table if not exists kpi_monthly (
    "month"                            text not null,
    "revenue_ex_vat"                   double precision,
    "n_documents"                      bigint,
    "selling_days"                     bigint,
    "n_customers"                      bigint,
    "revenue_per_selling_day"          double precision,
    "avg_document_value"               double precision,
    "pct_change_per_selling_day"       double precision,
    "is_partial_month"                 boolean,
    primary key ("month")
);

create table if not exists sales_by_group_month (
    "month"                            text not null,
    "category"                         text not null,
    "group_name"                       text not null,
    "revenue_ex_vat"                   double precision,
    "n_invoices"                       bigint,
    "n_lines"                          bigint,
    primary key ("month", "category", "group_name")
);
create index if not exists idx_sales_by_group_month_month on sales_by_group_month ("month");

create table if not exists sales_by_person_month (
    "month"                            text not null,
    "salesperson_code"                 text not null,
    "revenue_ex_vat"                   double precision,
    "n_invoices"                       bigint,
    primary key ("month", "salesperson_code")
);

create table if not exists model_accuracy (
    "scenario"                         text,
    "sku_prefix"                       text,
    "group_name"                       text,
    "model"                            text,
    "wape_weekly"                      double precision,
    "wape_4wk_total"                   double precision,
    "bias_4wk"                         double precision,
    "holdout_qty"                      double precision
);

create table if not exists dim_product_group (
    "sku_prefix"                       text not null,
    "category"                         text,
    "group_name"                       text,
    "unit"                             text,
    "forecast_scope"                   boolean,
    "is_intermittent"                  boolean,
    primary key ("sku_prefix")
);

-- ---------------------------------------------------------------
-- Row Level Security: signed-in users only.
-- The backend uses the service_role key and bypasses these; they
-- exist so that the anon key alone cannot read the data.
-- ---------------------------------------------------------------
alter table sales_header enable row level security;
drop policy if exists sales_header_read on sales_header;
create policy sales_header_read on sales_header for select to authenticated using (true);
alter table sales_lines enable row level security;
drop policy if exists sales_lines_read on sales_lines;
create policy sales_lines_read on sales_lines for select to authenticated using (true);
alter table deposits enable row level security;
drop policy if exists deposits_read on deposits;
create policy deposits_read on deposits for select to authenticated using (true);
alter table deposit_applications enable row level security;
drop policy if exists deposit_applications_read on deposit_applications;
create policy deposit_applications_read on deposit_applications for select to authenticated using (true);
alter table products enable row level security;
drop policy if exists products_read on products;
create policy products_read on products for select to authenticated using (true);
alter table customers enable row level security;
drop policy if exists customers_read on customers;
create policy customers_read on customers for select to authenticated using (true);
alter table customer_rfm enable row level security;
drop policy if exists customer_rfm_read on customer_rfm;
create policy customer_rfm_read on customer_rfm for select to authenticated using (true);
alter table customer_segments enable row level security;
drop policy if exists customer_segments_read on customer_segments;
create policy customer_segments_read on customer_segments for select to authenticated using (true);
alter table weekly_demand enable row level security;
drop policy if exists weekly_demand_read on weekly_demand;
create policy weekly_demand_read on weekly_demand for select to authenticated using (true);
alter table monthly_sales enable row level security;
drop policy if exists monthly_sales_read on monthly_sales;
create policy monthly_sales_read on monthly_sales for select to authenticated using (true);
alter table forecast_next_4_weeks enable row level security;
drop policy if exists forecast_next_4_weeks_read on forecast_next_4_weeks;
create policy forecast_next_4_weeks_read on forecast_next_4_weeks for select to authenticated using (true);
alter table trend_alerts enable row level security;
drop policy if exists trend_alerts_read on trend_alerts;
create policy trend_alerts_read on trend_alerts for select to authenticated using (true);
alter table reorder_points enable row level security;
drop policy if exists reorder_points_read on reorder_points;
create policy reorder_points_read on reorder_points for select to authenticated using (true);
alter table stock_check enable row level security;
drop policy if exists stock_check_read on stock_check;
create policy stock_check_read on stock_check for select to authenticated using (true);
alter table kpi_monthly enable row level security;
drop policy if exists kpi_monthly_read on kpi_monthly;
create policy kpi_monthly_read on kpi_monthly for select to authenticated using (true);
alter table sales_by_group_month enable row level security;
drop policy if exists sales_by_group_month_read on sales_by_group_month;
create policy sales_by_group_month_read on sales_by_group_month for select to authenticated using (true);
alter table sales_by_person_month enable row level security;
drop policy if exists sales_by_person_month_read on sales_by_person_month;
create policy sales_by_person_month_read on sales_by_person_month for select to authenticated using (true);
alter table model_accuracy enable row level security;
drop policy if exists model_accuracy_read on model_accuracy;
create policy model_accuracy_read on model_accuracy for select to authenticated using (true);
alter table dim_product_group enable row level security;
drop policy if exists dim_product_group_read on dim_product_group;
create policy dim_product_group_read on dim_product_group for select to authenticated using (true);
alter table upload_batches enable row level security;
drop policy if exists upload_batches_read on upload_batches;
create policy upload_batches_read on upload_batches for select to authenticated using (true);
